name: Manual Pipeline Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'  # Default value if not specified

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      
      - name: Print environment variable
        run: echo "Deploying to environment $ENVIRONMENT"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: run build
        run: npm run build

