name: Continuos Integration

on: 
  pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      MY_SECRET_ENV: ${{ secrets.MY_SECRET_ENV }}

    steps:
      - uses: actions/checkout@v3
      - name: Use secret as environment variable
        run: echo "The secret environment is $MY_SECRET_ENV"
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: run build
        run: npm run build
